controllers/UserController.php
<?php

namespace app\controllers;

use app\common\Constant;
use app\models\Account;
use app\models\SecurityForm;
use app\models\UserDetail;
use Yii;
use app\models\User;
use app\models\AddUserForm;
use app\models\UserSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $currentUser = User::findOne(['id' => Yii::$app->user->getId()]);
                            Yii::info('MGDEV - Current users type is: ' .$currentUser->type);

                            $isAdminUser = strcmp(Constant::USER_TYPE_ADMIN, $currentUser->type) === 0;
                            return $isAdminUser;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AddUserForm();

        if ($model->load(Yii::$app->request->post())) {

            $newUser = User::findOne(['email' => $model->email]);

            if ( isset($newUser) ) {
                return $this->render('view', [
                        'model' => $newUser,
                        'recordAlreadyExists' => true,
                    ]);
            } else {
                $newUser = new User();
                $newUser->artist = $model->artist;
                $newUser->email = $model->email;
                $newUser->type = $model->type;

                if ( $newUser->save(false) ) {
                    $hasEmailBeenSent = Yii::$app->mailer->compose('contact/account-created', ['user' => $newUser, 'password' => $newUser->raw_password])
                        ->setFrom('admin@nxew.ca')
                        ->setTo($newUser->email)
                        ->setSubject('Account Created')
                        ->send();

                    return $this->redirect(['view', 'id' => $newUser->id]);
                } else {
                    Yii::info("MGDEV - Failing to save");
                    return $this->render('create', [
                        'model' => $model,
                        'success' => false,
                        'errors' => $newUser->errors,
                    ]);
                }
            }


        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUserUpdate()
    {
        $userDetail = new UserDetail();
        if ($userDetail->load(Yii::$app->request->post())) {
            Yii::info('MGDEV - User detail update id recieved is: ' . $userDetail->artist);

            $user = User::findOne(['id' => Yii::$app->getUser()->id]);
            $user->artist = $userDetail->artist;

            $user->save();
            $account = Account::findOne(['user_id' => $user->id]);
        }

        return $this->redirect(['account/view']);
    }

    public function actionUserPasswordReset() {
        $securityForm = new SecurityForm();
        $userDetail = new UserDetail();

        $user = User::findOne(['id' => Yii::$app->getUser()->id]);
        $userDetail->artist = $user->artist;

        if ($securityForm->load(Yii::$app->request->post())) {

            if ( $securityForm->validate() ) {
                $user->updatePassword($securityForm->newPassword);
                Yii::info("MGDEV - Password has been updated to " . $securityForm->newPassword);

                return $this->render('../setting/update', [
                    'userDetail' => $userDetail,
                    'securityForm' => $securityForm,
                    'passwordUpdatedSuccessfully' => true,
                ]);
            } else {
                Yii::info('MGDEV - Password will not be updated');
                return $this->render('../setting/update', [
                    'userDetail' => $userDetail,
                    'securityForm' => $securityForm,
                    'securityFormErrors' => $securityForm->errors,
                ]);
            }
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $user = $this->findModel($id);

        if(isset($_POST['reset-password'])) {
            $user->resetPassword();
            $user->save();

            $hasEmailBeenSent = Yii::$app->mailer->compose('contact/password-reset', ['user' => $user])
                ->setFrom('password-reset@nxew.ca')
                ->setTo('me@mehaul.me')
                ->setSubject('Nxew - Password Reset')
                ->send();

            return $this->render('update', [
                'model' => $user,
                'isPasswordReset' => true,
            ]);
        } else {
            Yii::info('MGDEV - In the update action');
            $model = $this->findModel($id);
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                Yii::info('MGDEV - redirecting to the view');
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                Yii::info('MGDEV - rendering the update with id: ' . $model->email);
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }


        return $this->redirect(['view', 'id' => $user->id]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findModelByEmail($email)
    {
        if (($model = User::findOne(['email' => $email])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\common\Constant;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
        <link rel="shortcut icon" href="<?= Yii::$app->request->baseUrl . '/favicon.ico' ?>" type="image/x-icon">
        <link href='https://fonts.googleapis.com/css?family=Roboto:500,400,700' rel='stylesheet' type='text/css'>    </head>
    <body>
    <?php $this->beginBody() ?>

    <div class="wrap">
        <?php
        NavBar::begin([
            'brandLabel' => Html::img(Yii::$app->request->baseUrl . '/img/nxewlogo.png', ['height' => '60px']),
            'brandUrl' => Yii::$app->homeUrl,
            'brandOptions' => [
                'style' => 'padding: 0px;'
            ],
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
                'style' => 'background-color: #4b4b4b; height: 60px;'
            ],
        ]);

        $allMenuItems = [];
        $usersMenuItem = [];
        $loginMenuItem = [];

        if ( Yii::$app->user->isGuest ) {
            $loginMenuItem = ['label' => 'Login', 'url' => ['/login/login']];
            $contributeMenuItem = ['label' => 'Contribute', 'url' => ['/login/contribute']];
        } else {

            $loginMenuItem = [
                'label' => 'Logout (' . Yii::$app->user->identity->email . ')',
                'url' => ['/site/logout'],
                'linkOptions' => ['data-method' => 'post']
            ];

            // Add menu items that are only available to ADMIN users
            $userType = Yii::$app->session->get(Constant::USER_TYPE);
            if ( Constant::USER_TYPE_ADMIN === $userType) {
                $usersMenuItem = [
                    'label' => 'Users ',
                    'items' => [
                        ['url' => ['user/create'], 'label' => 'Add User'],
                        ['url' => ['user/index'], 'label' => 'List User', 'icon' => 'arrow-right', 'content' => $content],
                    ]
                ];
            }

            $accountMenuItem = [
                'label' => 'Account ',
                'url' => ['account/view']
            ];
        }

        if ( isset($contributeMenuItem) ) {
            array_push($allMenuItems, $contributeMenuItem);
        }

        if ( isset($accountMenuItem) ) {
            array_push($allMenuItems, $accountMenuItem);
        }
        if ( $usersMenuItem ) {
            array_push($allMenuItems, $usersMenuItem);
        }
        if ( $loginMenuItem ) {
            array_push($allMenuItems, $loginMenuItem);
        }

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $allMenuItems,
        ]);



        NavBar::end();
        ?>

        <div class="container">
            <?= $content ?>

        </div>
    </div>

    <div class="navbar navbar-fixed-bottom" style="background-color: #4b4b4b">
        <footer  style="background: #4b4b4b; padding-top: 0px" class="footer">
            
            <div class="col-lg-8 col-lg-offset-2">
                <div id="player">
                </div>
            </div>

        </footer>
    </div>

    <?php $this->endBody() ?>
    

    <script>
            if ( trackUrls != undefined ) {
            (function() {

            }());

            ToneDenReady = window.ToneDenReady || [];
            ToneDenReady.push(function() {
                ToneDen.configure({
                    soundcloudConsumerKey: '75e6c4a9b578f90c37c810f32675f126'
                });
                // This is where all the action happens:
                ToneDen.player.create({
                    dom: "#player",
                    eq: "waves",
                    skin: "dark",
                    mini: true,
                    urls: trackUrls,
                    debug: true
                });
            });
        }
    </script>





    </body>
    </html>
<?php $this->endPage() ?>