models/Setting.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "setting".
 *
 * @property string $name
 * @property string $value
 */
class Setting extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'setting';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['value'], 'required'],
            [['value'], 'string'],
            [['name'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => 'Name',
            'value' => 'Value',
        ];
    }

    public static function findByName($settingName) {
        return Setting::findOne(['name' => $settingName]);
    }
}

controllers/SettingController.php
<?php

namespace app\controllers;

use app\models\AddTrackSoundCloudForm;
use app\models\PlaylistTrack;
use app\models\SecurityForm;
use app\models\User;
use app\models\Setting;
use Yii;
use app\models\Account;
use app\models\AccountSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Html;
use app\common\Constant;

/**
 * AccountController implements the CRUD actions for Account model.
 */
class SettingController extends Controller
{
   function actionUpdate($name) {
   		$model = Setting::findByName($name);
   		$model->load(Yii::$app->request->post());

        $model->save();
        
    	return $this->redirect(['account/view']);
   }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\common\Constant;
use app\models\Account;
use app\models\SecurityForm;
use app\models\UserDetail;
use Yii;
use app\models\User;
use app\models\AddUserForm;
use app\models\UserSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $currentUser = User::findOne(['id' => Yii::$app->user->getId()]);
                            Yii::info('MGDEV - Current users type is: ' .$currentUser->type);

                            $isAdminUser = strcmp(Constant::USER_TYPE_ADMIN, $currentUser->type) === 0;
                            return $isAdminUser;
                        }
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new AddUserForm();

        if ($model->load(Yii::$app->request->post())) {

            $newUser = User::findOne(['email' => $model->email]);

            if ( isset($newUser) ) {
                return $this->render('view', [
                        'model' => $newUser,
                        'recordAlreadyExists' => true,
                    ]);
            } else {
                $newUser = new User();
                $newUser->artist = $model->artist;
                $newUser->email = $model->email;
                $newUser->type = $model->type;

                if ( $newUser->save(false) ) {
                    $hasEmailBeenSent = Yii::$app->mailer->compose('contact/account-created', ['user' => $newUser, 'password' => $newUser->raw_password])
                        ->setFrom('admin@nxew.ca')
                        ->setTo($newUser->email)
                        ->setSubject('Account Created')
                        ->send();

                    return $this->redirect(['view', 'id' => $newUser->id]);
                } else {
                    Yii::info("MGDEV - Failing to save");
                    return $this->render('create', [
                        'model' => $model,
                        'success' => false,
                        'errors' => $newUser->errors,
                    ]);
                }
            }


        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUserUpdate()
    {
        $userDetail = new UserDetail();
        if ($userDetail->load(Yii::$app->request->post())) {
            Yii::info('MGDEV - User detail update id recieved is: ' . $userDetail->artist);

            $user = User::findOne(['id' => Yii::$app->getUser()->id]);
            $user->artist = $userDetail->artist;

            $user->save();
            $account = Account::findOne(['user_id' => $user->id]);
        }

        return $this->redirect(['account/view']);
    }

    public function actionUserPasswordReset() {
        $securityForm = new SecurityForm();
        $userDetail = new UserDetail();

        $user = User::findOne(['id' => Yii::$app->getUser()->id]);
        $userDetail->artist = $user->artist;

        if ($securityForm->load(Yii::$app->request->post())) {

            if ( $securityForm->validate() ) {
                $user->updatePassword($securityForm->newPassword);
                Yii::info("MGDEV - Password has been updated to " . $securityForm->newPassword);

                return $this->render('../setting/update', [
                    'userDetail' => $userDetail,
                    'securityForm' => $securityForm,
                    'passwordUpdatedSuccessfully' => true,
                ]);
            } else {
                Yii::info('MGDEV - Password will not be updated');
                return $this->render('../setting/update', [
                    'userDetail' => $userDetail,
                    'securityForm' => $securityForm,
                    'securityFormErrors' => $securityForm->errors,
                ]);
            }
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $user = $this->findModel($id);

        if(isset($_POST['reset-password'])) {
            $user->resetPassword();
            $user->save();

            $hasEmailBeenSent = Yii::$app->mailer->compose('contact/password-reset', ['user' => $user])
                ->setFrom('password-reset@nxew.ca')
                ->setTo('me@mehaul.me')
                ->setSubject('Nxew - Password Reset')
                ->send();

            return $this->render('update', [
                'model' => $user,
                'isPasswordReset' => true,
            ]);
        } else {
            Yii::info('MGDEV - In the update action');
            $model = $this->findModel($id);
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                Yii::info('MGDEV - redirecting to the view');
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                Yii::info('MGDEV - rendering the update with id: ' . $model->email);
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }


        return $this->redirect(['view', 'id' => $user->id]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findModelByEmail($email)
    {
        if (($model = User::findOne(['email' => $email])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/setting/update.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update Settings';
?>
<div class="account-create">

<h1><?= Html::encode($this->title) ?></h1>


<?php if ( (isset($isUpdated) ? $isUpdated : false) ) {
    $options = ['class' =>'alert alert-success'];
    echo Html::tag('div', '<strong>Updated!</strong> Bio updated successfully.', $options);
}?>

<?php if ( (isset($isSaved) ? $isSaved : false) ) {
    $options = ['class' =>'alert alert-success'];
    echo Html::tag('div', '<strong>Saved!</strong> Bio created successfully.', $options);
}?>
<link href="../vendor/bower/bootstrap-fileinput/css/fileinput.min.css" media="all" rel="stylesheet" type="text" />
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js" type="text/javascript"></script>
<script src="../vendor/bower/bootstrap-fileinput/js/fileinput.js" type="text/javascript"></script>

<div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Avatar
                </h3>
            </div>
            <div class="panel-body">

                <input id="input-id" type="file" class="file" data-preview-file-type="text">

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Playlist Name
                </h3>
            </div>
            <div class="panel-body">
                <?php
                $form = ActiveForm::begin(['id' => 'update-account', 'action' => Yii::$app->getUrlManager()->createUrl(['account/update-playlist-name'])]);

                echo $form->field($account, 'playlist_name');
                echo Html::submitButton('Update', ['class' => 'btn btn-primary']);

                ActiveForm::end();
                ?>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Details
                </h3>
            </div>
            <div class="panel-body">
                <?php
                    $form = ActiveForm::begin(['id' => 'update-account', 'action' => Yii::$app->getUrlManager()->createUrl(['user/user-update'])]);

                    echo $form->field($userDetail, 'forename');
                    echo $form->field($userDetail, 'surname');

                    echo Html::submitButton('Update', ['class' => 'btn btn-primary']);

                    ActiveForm::end();
                ?>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-6 col-sm-6 col-xs-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Security
                </h3>
            </div>
            <div class="panel-body">
                <?php
                    if ( (isset($passwordUpdatedSuccessfully) ? $passwordUpdatedSuccessfully : false) ) {
                        $options = ['class' =>'alert alert-success'];
                        echo Html::tag('div', '<strong>Updated!</strong> Password updated successfully.', $options);
                    }

                    $form = ActiveForm::begin(['id' => 'update-password', 'action' => Yii::$app->getUrlManager()->createUrl('user/user-password-reset')]);

                    echo $form->field($securityForm, 'currentPassword')->passwordInput();
                    echo $form->field($securityForm, 'newPassword')->passwordInput();
                    echo $form->field($securityForm, 'newPasswordAgain')->passwordInput();

                    echo Html::submitButton('Reset', ['class' => 'btn btn-primary']);

                    ActiveForm::end();
                ?>
            </div>
        </div>
    </div>
</div>



</div>