controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\SecurityForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\AddUserForm;
use app\models\ContactForm;
use app\common\Constant;
use app\models\User;
use app\models\Account;
use app\models\PlaylistTrack;



class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout','reset-password'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['reset-password'],
                        'roles' => ['?'],
                        'matchCallback' => function ($rule, $action) {
                            Yii::info('MGDEV - testing reset-password');
                            Yii::info('MGDEV - token is ' . Yii::$app->request->get('token'));
                            $currentUser = User::findOne(['password_reset_token' => Yii::$app->request->get('token')]);

                            return isset($currentUser);
                        }
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $account = Account::findRandom();

        $user = User::findOne(['id' => $account->user_id]);
        $playlistTracks = PlaylistTrack::findAll(['account_id' => $account->id]);


        Yii::info('MGDEV - we should have a user account for: ' . $account->user_id);

        $doesUserOwnPlaylist = Yii::$app->getUser()->id == $account->user_id;


        return $this->render('random-playlist', [
            'playlistTracks' => $playlistTracks,
            'account' => $account,
            'user' => $user,
            'doesUserOwnPlaylist' => $doesUserOwnPlaylist
        ]);
    }


    public function actionContribute()
    {
        return $this->render('contribute');
    }

    public function actionLogin()
    {
        Yii::info('MGDEV - actionLogin() has been called' );
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->session->set(Constant::USER_TYPE, $model->type);
            Yii::info('MGDEV - We are where we\'re expected');
            return $this->redirect(['account/view']);
        }

        return $this->render('../login/login', [
            'model' => $model,
            'passwordReset' => false,
        ]);
    }

    public function actionResetPassword() {

        $securityForm = new SecurityForm();
        $passwordUpdated = false;

        $token = Yii::$app->request->get('token');
        $user = User::findOne(['password_reset_token' => $token]);


        Yii::info('MGDEV - attempting to reset the password');

        if ($securityForm->load(Yii::$app->request->post())) {
            Yii::info('MgDEV - password reset token in actionResetPassword is ' . $token);

            if ( isset($user) ) {

                Yii::info('MGDEV - got the user');

                $user->updatePassword($securityForm->newPasswordAgain);

                Yii::info('MGDEV - Reset the password. Now redirecting');

                return $this->render('../login/login', [
                    'model' =>  new LoginForm(),
                    'passwordReset' => false,
                ]);
            }
        } else {
            Yii::info('MGDEV - failed to reset the password');
        }

        Yii::info('MGDEV - We are calling the security form with the token: ' . $token);
        $securityForm->token = $token;

        return $this->render('reset-password', [
            'securityForm' => $securityForm,
        ]);
    }

    public function actionAsdfQwerty() {
        $this->redirect('http://www.google.com');
    }

    public function actionRandomPlaylist() {

        $account = Account::findRandom();

        $user = User::findOne(['id' => $account->user_id]);
        $playlistTracks = PlaylistTrack::findAll(['account_id' => $account->id]);


        $doesUserOwnPlaylist = Yii::$app->getUser()->id == $account->user_id;

        Yii::info('MGDEV - we should have a user account for: ' . $account->user_id);


        return $this->render('random-playlist', [
            'playlistTracks' => $playlistTracks,
            'account' => $account,
            'user' => $user,
            'doesUserOwnPlaylist' => $doesUserOwnPlaylist
        ]);
    }

    public function actionRequestPasswordReset() {
        $user = new User();

        Yii::info('MGDEV - requesting reset');
        if ($user->load(Yii::$app->request->post())) {
            Yii::info('MGDEV - Loading user');
            $user = User::findByEmail($user->email);
            $foundUser = isset($user);

            if ( $foundUser ) {
                Yii::info('MGDEV - Found user');
                $user->resetPassword();
                $user->save(false);

                Yii::$app->mailer->compose('contact/password-reset', ['user' => $user])
                    ->setFrom('password-reset@nxew.ca')
                    ->setTo('me@mehaul.me')
                    ->setSubject('Nxew - Password Reset')
                    ->send();
            } else {
                $user = new User();
            }

            return $this->render('request-password-reset', [
                'model' => $user,
                'foundUser' => $foundUser
            ]);
        }

        return $this->render('request-password-reset', [
            'model' => $user,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        if (\Yii::$app->user->isGuest) {
            return $this->render('error', ['name' => 'Not authorized', 'message' => 'Please log in to view this page']);
        } else {
            return $this->render('about');
        }
        
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/contribute.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
$this->title = 'Contribute';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Nxew!</h1>

        <p class="lead">Discover while being discovered.</p>

    </div>

    <div class="body-content">

        <div class="row">
            
            <div class="col-lg-6 text-right">
                <?php
                    if ( Yii::$app->user->isGuest ) {
                        echo '<p>' . Html::a('Login', ['site/login'], ['class' => 'btn btn-lg btn-success home-page-buttons']) . '</p>';
                    } else {
                        echo '<p>' . Html::a('Edit Profile', ['site/login'], ['class' => 'btn btn-lg btn-success home-page-buttons']) . '</p>';
                    }
                ?>
            </div>
            <div class="col-lg-6">
                <?php
                    $options = ['class' => 'btn btn-lg btn-primary home-page-buttons'];
                    echo Html::a('Random Playlist', ['site/random-playlist'], $options);
                ?>
            </div>
            
        </div>

    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
$this->title = 'Nxew';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Nxew!</h1>

        <p class="lead">Discover while being discovered.</p>

    </div>

    <div class="body-content">

        <div class="row">
            
            <div class="col-lg-6 text-right">
                <?php
                    if ( Yii::$app->user->isGuest ) {
                        echo '<p>' . Html::a('Login', ['site/login'], ['class' => 'btn btn-lg btn-success home-page-buttons']) . '</p>';
                    } else {
                        echo '<p>' . Html::a('Edit Profile', ['site/login'], ['class' => 'btn btn-lg btn-success home-page-buttons']) . '</p>';
                    }
                ?>
            </div>
            <div class="col-lg-6">
                <?php
                    $options = ['class' => 'btn btn-lg btn-primary home-page-buttons'];
                    echo Html::a('Random Playlist', ['site/random-playlist'], $options);
                ?>
            </div>
            
        </div>

    </div>
</div>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Login';
?>

<?php
Yii::info('MGDEV - Password rest is: ' . isset($passwordReset) ? $passwordReset : false);
if ( isset($passwordReset) ? $passwordReset : false ) {
?>
    <div class="row center-block">
        <div class="col-xs-4 col-xs-offset-4 col-lg-41">
            <?php
                $options = ['class' =>'alert alert-success'];
                echo Html::tag('div', '<strong>Updated!</strong> Password updated successfully.', $options);
            ?>
        </div>
    </div>
<?php
}
?>


<div class="row center-block" >
    <div class="col-xs-12 col-lg-4 col-lg-offset-4" style="margin-top: 100px">
        <div class="panel">
            <div class="panel-body">
                partial render
            <?= $this->render('_form') ?>

            </div>
        </div>
    </div>
</div>

views/site/random-playlist.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Random Playlist';
?>
<div class="account-view">

    <div class="row account-view-row">
        <div class="col-md-4 col-lg-4 col-sm-5">
            <?= $this->render('../account/_profile', [
                'account' => $account,
                'user' => $user,
                'doesUserOwnPlaylist' => $doesUserOwnPlaylist
            ]) ?>
        </div>
        <div class="col-md-8 col-lg-8 col-sm-7">
            <?= $this->render('../account/_playlist', [
                'account' => $account,
                'user' => $user,
                'addSoundCloud' => null,
                'playlistTracks' => $playlistTracks,
                'maxNumberOfTracksReached' => null,
                'doesUserOwnPlaylist' => $doesUserOwnPlaylist
            ]) ?>
        </div>
    </div>
</div>

views/site/request-password-reset.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Password reset';
?>

<div class="row">
    <?php
        $showResetFuncitonality = true;
        if ( isset($foundUser) ) {
            if ( $foundUser) { 
                    $showResetFuncitonality = false;    
                ?>
                <div class="password-reset-panel-success col-xs-12 col-lg-8 col-lg-offset-2" style="margin-top: 100px; border: 0px solid black; max-height: 380px">
                    <div class="col-xs-12 col-lg-12">
                        <div class="panel">
                            <h2 class="panel-body title text-center">We found you!</h2>
                            <div class="panel-body contribute-text text-center">
                                <p>
                                    An email is on it's way with a password reset link.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
           <?php
            } else {
            ?>
                <div class="password-reset-panel-fail col-xs-12 col-lg-8 col-lg-offset-2" style="margin-top: 100px; border: 0px solid black; max-height: 380px">
                    <div class="col-xs-12 col-lg-12">
                        <div class="panel">
                            <h2 class="panel-body title text-center">Not Found!</h2>
                            <div class="panel-body contribute-text text-center">
                                <p>
                                    We are unable to find any record of that email address.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            <?php
            }
        }
    ?>
</div>
<?php
    if ( $showResetFuncitonality ) {
?>
    <div class="row center-block" >
        <div class="col-xs-12 col-lg-4 col-lg-offset-4" style="margin-top: 100px">
            <div class="panel">
                <div class="panel-body">
                    <?php $form = ActiveForm::begin(['id' => 'request-password-reset']); ?>
                    <?= $form->field($model, 'email')->textInput(['placeholder' => 'EMAIL', 'class' => 'form-control login-password'])->label('') ?>
                    <div class="form-group" style="text-align:center">
                        <?= Html::submitButton('RESET MY PASSWORD', ['class' => 'btn login-button', 'name' => 'add-user-button']) ?>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
<?php
    }
?>

views/site/reset-password.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'New Password';
?>

<div class="user-form">

    <div class="row center-block" >
        <div class="col-xs-4 col-xs-offset-4 col-lg-4 col-lg-offset-4" style="margin-top: 100px">
            <div class="panel">
                <div class="panel-body">

                    <?php
                        if ( (isset($passwordUpdatedSuccessfully) ? $passwordUpdatedSuccessfully : false) ) {
                            $options = ['class' =>'alert alert-success'];
                            echo Html::tag('div', '<strong>Updated!</strong> Password updated successfully.', $options);
                        }

                        $form = ActiveForm::begin(['id' => 'reset-password', 'action' => Yii::$app->getUrlManager()->createUrl(['site/reset-password', 'token' => $securityForm->token])]);

                        echo $form->field($securityForm, 'newPassword')->passwordInput(['placeholder' => 'NEW PASSWORD', 'class' => 'form-control login-password'])->label('');
                        echo $form->field($securityForm, 'newPasswordAgain')->passwordInput(['placeholder' => 'REPEAT NEW PASSWORD', 'class' => 'form-control login-password'])->label('');

                    ?>
                        <div class="form-group" style="text-align:center">
                            <?= Html::submitButton('I\'LL REMEBER IT THIS TIME', ['class' => 'btn login-button']) ?>
                        </div>
                    <?php
                        ActiveForm::end();
                    ?>

                </div>
            </div>
        </div>
    </div>
    

</div>